### ISSUE TITLE
java.lang.IllegalStateException: Can't compress a recycled bitmap

### ISSUE THREAD

**Issue by libinmath3w** [Slion/Fulguris#101]
```
java.lang.IllegalStateException: Can't compress a recycled bitmap
    at android.graphics.Bitmap.checkRecycled(Bitmap.java:407)
    at android.graphics.Bitmap.compress(Bitmap.java:1627)
    at c.a.a.a.t.r
    at com.ulgurisbrowser.activity.BrowserActivity.m0
    at com.ulgurisMainActivity.onPause
    at android.app.Activity.performPause(Activity.java:7652)
    at android.app.Instrumentation.callActivityOnPause(Instrumentation.java:1469)
    at android.app.ActivityThread.performPauseActivityIfNeeded(ActivityThread.java:4284)
    at android.app.ActivityThread.performPauseActivity(ActivityThread.java:4249)
    at android.app.ActivityThread.handlePauseActivity(ActivityThread.java:4201)
    at android.app.servertransaction.PauseActivityItem.execute(PauseActivityItem.java:45)
    at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:145)
    at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:70)
    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1970)
    at android.os.Handler.dispatchMessage(Handler.java:106)
    at android.os.Looper.loop(Looper.java:214)
    at android.app.ActivityThread.main(ActivityThread.java:7156)
    at java.lang.reflect.Method.invoke(Method.java)
    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:494)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:975)

java.lang.RuntimeException: Unable to pause activity {com.fulguris.web/com.ulgurisMainActivity}: java.lang.IllegalStateException: Can't compress a recycled bitmap
    at android.app.ActivityThread.performPauseActivityIfNeeded(ActivityThread.java:4294)
    at android.app.ActivityThread.performPauseActivity(ActivityThread.java:4249)
    at android.app.ActivityThread.handlePauseActivity(ActivityThread.java:4201)
    at android.app.servertransaction.PauseActivityItem.execute(PauseActivityItem.java:45)
    at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:145)
    at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:70)
    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1970)
    at android.os.Handler.dispatchMessage(Handler.java:106)
    at android.os.Looper.loop(Looper.java:214)
    at android.app.ActivityThread.main(ActivityThread.java:7156)
    at java.lang.reflect.Method.invoke(Method.java)
    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:494)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:975)
```

**Comment by Slion** [comment]
Thanks for reporting that issue. Could you tell me when this is happening? Which device and OS?

**Comment by libinmath3w** [comment]
Architecture | arm64-v8a
-- | --
Architectures | [arm64-v8a, armeabi-v7a, armeabi]
Battery Level | 77%
Boot Time | 2020-12-12T05:54:19.802Z
Brand | Nokia
Charging | False
Connection Type | cellular
Family | Nokia
Free Memory | 1.3 GB
Free Storage | 5.3 GB
Id | 7e4809ab9a922622
Language | en_US
Low Memory | False
Manufacturer | HMD Global
Memory Size | 3.6 GB
Model | Nokia 6.1 (QKQ1.190828.002)
Model Id | QKQ1.190828.002
Name | Nokia 6.1
Online | True
Orientation | portrait
Screen Density | 2.875
Screen DPI | 460
Screen Height Pixels | 1794
Screen Resolution | 1794x1080
Screen Width Pixels | 1080
Simulator | False
Storage Size | 48.2 GB
Timezone | Asia/Kolkata

**Comment by Slion** [comment]
@libinmath3w Is this still an issue for you? I'm thinking this was resolved in one of the many changes done for the sessions feature implementation.

**Comment by Slion** [comment]
Assuming this was fixed. Please reopen if needed.
