### ISSUE TITLE
App doesn't start anymore because this RxJava error

### ISSUE THREAD

**Issue by jamal2362** [Slion/Fulguris#102]
This error has already appeared on 2 devices. Only deleting app data helped. 

k.a.y.c: The exception was not handled due to missing onError handler in the subscribe() method call. Further reading: https://github.com/ReactiveX/RxJava/wiki/Error-Handling | java.lang.IllegalArgumentException
	at k.a.b0.b.a$f.accept(:1)
	at k.a.b0.d.e.a(Unknown Source:7)
	at k.a.b0.e.f.e$a.a(Unknown Source:2)
	at k.a.b0.e.e.j$a.a(Unknown Source:9)
	at k.a.b0.d.a.a(Unknown Source:13)
	at k.a.b0.e.e.l$a.e(Unknown Source:47)
	at k.a.b0.e.e.l$a.run(:2)
	at k.a.w.a.b$b.run(Unknown Source:2)
	at android.os.Handler.handleCallback(Handler.java:883)
	at android.os.Handler.dispatchMessage(Handler.java:100)
	at android.os.Looper.loop(Looper.java:219)
	at android.app.ActivityThread.main(ActivityThread.java:7709)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:516)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:950)
Caused by: java.lang.IllegalArgumentException
	at android.os.Parcel.nativeAppendFrom(Native Method)
	at android.os.Parcel.appendFrom(Parcel.java:563)
	at android.os.BaseBundle.readFromParcelInner(BaseBundle.java:1646)
	at android.os.BaseBundle.<init>(BaseBundle.java:143)
	at android.os.Bundle.<init>(Bundle.java:95)
	at android.os.Parcel.readBundle(Parcel.java:2284)
	at c.a.a.k.s.apply(:7)
	at k.a.b0.e.d.a$a.f(Unknown Source:2)
	at k.a.b0.e.f.o$a.run(Unknown Source:14)
	at k.a.b0.g.h.call(:1)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:919)

**Comment by Slion** [comment]
I've never seen that. Do you know how to reproduce it?
Maybe it is caused by a specific web site you usually visit somehow.
Is it an issue while loading the persisted tabs?

On which devices have you had those issues?
Which OS and version?

Could it be that's a regression introduced in your fork?
Was that fixing your issue: https://github.com/jamal2362/Styx/commit/fab8441ab81eff9d8d2a70141d35c76855cf773f

BTW your fork is in breach of the Fulguris license and copyright. You must not remove Fulguris copyright.

**Comment by jamal2362** [comment]
Hi,
There are now 3 devices
A OnePlus 8 Pro with OOS 11, OnePlus 7 Pro with OOS 10 and a OnePlus 5 with LineageOS 17.1

We can not reproduce it exactly, with me it did not open after quitting when I wanted to open it again, with my colleague it did not open overnight when he got up in the morning. And with the OnePlus 5 it also no longer went on the browser.

 It's always the same error in Logcat on all 3 devices. However, this only occurs very late after about 1 week of use.

Sorry for removing the copyright. I accidentally replaced the line with my name. I have added it back in the readme.

**Comment by Slion** [comment]
Do you have the same issue with Fulguris or is it just with Styx? Try reproducing it with the Google Play variant.

**Comment by jamal2362** [comment]
I will try and give you a Feedback :)

**Comment by jamal2362** [comment]
This can be closed. I think it's fixed for me :)
