### ISSUE TITLE
Content control settings crash

### ISSUE THREAD

**Issue by Slion** [Slion/Fulguris#221]
# Description
Crash when opening content control settings

# Environment
 - Device: Samsung Galaxy S7 Edge
 - OS: Android 8
 - Version: main

# To reproduce
Steps to reproduce the behaviour:
1. Go to content control settings and turn it on
2. App crash
3. Launch app again
4. Go to content control settings 
5. App crash

# Expected behaviour
Should not crash

# Screenshots
None

# Additional context
Looks like it's trying to access a file that's not there and can't recover from that because of missing error handler.

## Logs

`2021-07-22 14:45:25.411 23287-23287/net.slions.fulguris.full.download.debug D/ViewRootImpl@fb3f30c[SettingsActivity]: ViewPostIme pointer 0
2021-07-22 14:45:25.478 23287-23287/net.slions.fulguris.full.download.debug D/ViewRootImpl@fb3f30c[SettingsActivity]: ViewPostIme pointer 1
2021-07-22 14:45:25.523 23287-23287/net.slions.fulguris.full.download.debug D/ViewRootImpl@fb3f30c[SettingsActivity]: Relayout returned: old=[0,0][1080,1920] new=[0,0][1080,1920] result=0x1 surface={valid=true 513145536512} changed=false
2021-07-22 14:45:25.693 23287-23287/net.slions.fulguris.full.download.debug V/InputMethodManager: Starting input: tba=android.view.inputmethod.EditorInfo@c07c92 nm : net.slions.fulguris.full.download.debug ic=null
2021-07-22 14:45:25.693 23287-23287/net.slions.fulguris.full.download.debug I/InputMethodManager: startInputInner - mService.startInputOrWindowGainedFocus
2021-07-22 14:45:25.805 23287-23287/net.slions.fulguris.full.download.debug W/System.err: io.reactivex.exceptions.OnErrorNotImplementedException: The exception was not handled due to missing onError handler in the subscribe() method call. Further reading: https://github.com/ReactiveX/RxJava/wiki/Error-Handling | java.io.FileNotFoundException: hosts.txt
2021-07-22 14:45:25.805 23287-23287/net.slions.fulguris.full.download.debug W/System.err:     at io.reactivex.internal.functions.Functions$OnErrorMissingConsumer.accept(Functions.java:704)
2021-07-22 14:45:25.805 23287-23287/net.slions.fulguris.full.download.debug W/System.err:     at io.reactivex.internal.functions.Functions$OnErrorMissingConsumer.accept(Functions.java:701)
2021-07-22 14:45:25.805 23287-23287/net.slions.fulguris.full.download.debug W/System.err:     at io.reactivex.internal.operators.maybe.MaybeCallbackObserver.onError(MaybeCallbackObserver.java:82)
2021-07-22 14:45:25.805 23287-23287/net.slions.fulguris.full.download.debug W/System.err:     at io.reactivex.internal.operators.maybe.MaybeObserveOn$ObserveOnMaybeObserver.run(MaybeObserveOn.java:98)
2021-07-22 14:45:25.805 23287-23287/net.slions.fulguris.full.download.debug W/System.err:     at io.reactivex.android.schedulers.HandlerScheduler$ScheduledRunnable.run(HandlerScheduler.java:124)
2021-07-22 14:45:25.805 23287-23287/net.slions.fulguris.full.download.debug W/System.err:     at android.os.Handler.handleCallback(Handler.java:789)
2021-07-22 14:45:25.806 23287-23287/net.slions.fulguris.full.download.debug W/System.err:     at android.os.Handler.dispatchMessage(Handler.java:98)
2021-07-22 14:45:25.806 23287-23287/net.slions.fulguris.full.download.debug W/System.err:     at android.os.Looper.loop(Looper.java:164)
2021-07-22 14:45:25.806 23287-23287/net.slions.fulguris.full.download.debug W/System.err:     at android.app.ActivityThread.main(ActivityThread.java:6944)
2021-07-22 14:45:25.806 23287-23287/net.slions.fulguris.full.download.debug W/System.err:     at java.lang.reflect.Method.invoke(Native Method)
2021-07-22 14:45:25.806 23287-23287/net.slions.fulguris.full.download.debug W/System.err:     at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:327)
2021-07-22 14:45:25.806 23287-23287/net.slions.fulguris.full.download.debug W/System.err:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1374)
2021-07-22 14:45:25.806 23287-23287/net.slions.fulguris.full.download.debug W/System.err: Caused by: java.io.FileNotFoundException: hosts.txt
2021-07-22 14:45:25.806 23287-23287/net.slions.fulguris.full.download.debug W/System.err:     at android.content.res.AssetManager.openAsset(Native Method)
2021-07-22 14:45:25.806 23287-23287/net.slions.fulguris.full.download.debug W/System.err:     at android.content.res.AssetManager.open(AssetManager.java:388)
2021-07-22 14:45:25.806 23287-23287/net.slions.fulguris.full.download.debug W/System.err:     at android.content.res.AssetManager.open(AssetManager.java:362)
2021-07-22 14:45:25.806 23287-23287/net.slions.fulguris.full.download.debug W/System.err:     at acr.browser.lightning.adblock.source.AssetsHostsDataSource.loadHosts$lambda-0(AssetsHostsDataSource.kt:30)
2021-07-22 14:45:25.806 23287-23287/net.slions.fulguris.full.download.debug W/System.err:     at acr.browser.lightning.adblock.source.AssetsHostsDataSource.lambda$AUqAI_nLNGUyi9nTDq-PnsEDIzU(Unknown Source:0)
2021-07-22 14:45:25.806 23287-23287/net.slions.fulguris.full.download.debug W/System.err:     at acr.browser.lightning.adblock.source.-$$Lambda$AssetsHostsDataSource$AUqAI_nLNGUyi9nTDq-PnsEDIzU.subscribe(Unknown Source:2)
2021-07-22 14:45:25.806 23287-23287/net.slions.fulguris.full.download.debug W/System.err:     at io.reactivex.internal.operators.single.SingleCreate.subscribeActual(SingleCreate.java:39)
2021-07-22 14:45:25.806 23287-23287/net.slions.fulguris.full.download.debug W/System.err:     at io.reactivex.Single.subscribe(Single.java:3666)
2021-07-22 14:45:25.806 23287-23287/net.slions.fulguris.full.download.debug W/System.err:     at io.reactivex.internal.operators.single.SingleFlatMapMaybe.subscribeActual(SingleFlatMapMaybe.java:41)
2021-07-22 14:45:25.806 23287-23287/net.slions.fulguris.full.download.debug W/System.err:     at io.reactivex.Maybe.subscribe(Maybe.java:4290)
2021-07-22 14:45:25.807 23287-23287/net.slions.fulguris.full.download.debug W/System.err:     at io.reactivex.internal.operators.maybe.MaybeFlatMapSingleElement.subscribeActual(MaybeFlatMapSingleElement.java:45)
2021-07-22 14:45:25.807 23287-23287/net.slions.fulguris.full.download.debug W/System.err:     at io.reactivex.Maybe.subscribe(Maybe.java:4290)
2021-07-22 14:45:25.807 23287-23287/net.slions.fulguris.full.download.debug W/System.err:     at io.reactivex.internal.operators.maybe.MaybeSwitchIfEmpty$SwitchIfEmptyMaybeObserver.onComplete(MaybeSwitchIfEmpty.java:88)
2021-07-22 14:45:25.807 23287-23287/net.slions.fulguris.full.download.debug W/System.err:     at io.reactivex.internal.operators.maybe.MaybeFilter$FilterMaybeObserver.onComplete(MaybeFilter.java:102)
2021-07-22 14:45:25.807 23287-23287/net.slions.fulguris.full.download.debug W/System.err:     at io.reactivex.internal.operators.maybe.MaybeFromCallable.subscribeActual(MaybeFromCallable.java:59)
2021-07-22 14:45:25.807 23287-23287/net.slions.fulguris.full.download.debug W/System.err:     at io.reactivex.Maybe.subscribe(Maybe.java:4290)
2021-07-22 14:45:25.807 23287-23287/net.slions.fulguris.full.download.debug W/System.err:     at io.reactivex.internal.operators.maybe.MaybeFilter.subscribeActual(MaybeFilter.java:39)
2021-07-22 14:45:25.807 23287-23287/net.slions.fulguris.full.download.debug W/System.err:     at io.reactivex.Maybe.subscribe(Maybe.java:4290)
2021-07-22 14:45:25.807 23287-23287/net.slions.fulguris.full.download.debug W/System.err:     at io.reactivex.internal.operators.maybe.MaybeSwitchIfEmpty.subscribeActual(MaybeSwitchIfEmpty.java:38)
2021-07-22 14:45:25.807 23287-23287/net.slions.fulguris.full.download.debug W/System.err:     at io.reactivex.Maybe.subscribe(Maybe.java:4290)
2021-07-22 14:45:25.807 23287-23287/net.slions.fulguris.full.download.debug W/System.err:     at io.reactivex.internal.operators.single.SingleFlatMapMaybe$FlatMapSingleObserver.onSuccess(SingleFlatMapMaybe.java:89)
2021-07-22 14:45:25.807 23287-23287/net.slions.fulguris.full.download.debug W/System.err:     at io.reactivex.internal.operators.single.SingleFromCallable.subscribeActual(SingleFromCallable.java:56)
2021-07-22 14:45:25.807 23287-23287/net.slions.fulguris.full.download.debug W/System.err:     at io.reactivex.Single.subscribe(Single.java:3666)
2021-07-22 14:45:25.807 23287-23287/net.slions.fulguris.full.download.debug W/System.err:     at io.reactivex.internal.operators.single.SingleFlatMapMaybe.subscribeActual(SingleFlatMapMaybe.java:41)
2021-07-22 14:45:25.807 23287-23287/net.slions.fulguris.full.download.debug W/System.err:     at io.reactivex.Maybe.subscribe(Maybe.java:4290)
2021-07-22 14:45:25.807 23287-23287/net.slions.fulguris.full.download.debug W/System.err:     at io.reactivex.internal.operators.maybe.MaybeFilter.subscribeActual(MaybeFilter.java:39)
2021-07-22 14:45:25.808 23287-23287/net.slions.fulguris.full.download.debug W/System.err:     at io.reactivex.Maybe.subscribe(Maybe.java:4290)
2021-07-22 14:45:25.808 23287-23287/net.slions.fulguris.full.download.debug W/System.err:     at io.reactivex.internal.operators.maybe.MaybeSubscribeOn$SubscribeTask.run(MaybeSubscribeOn.java:54)
2021-07-22 14:45:25.808 23287-23287/net.slions.fulguris.full.download.debug W/System.err:     at io.reactivex.internal.schedulers.ScheduledDirectTask.call(ScheduledDirectTask.java:38)
2021-07-22 14:45:25.808 23287-23287/net.slions.fulguris.full.download.debug W/System.err:     at io.reactivex.internal.schedulers.ScheduledDirectTask.call(ScheduledDirectTask.java:26)
2021-07-22 14:45:25.808 23287-23287/net.slions.fulguris.full.download.debug W/System.err:     at java.util.concurrent.FutureTask.run(FutureTask.java:266)
2021-07-22 14:45:25.808 23287-23287/net.slions.fulguris.full.download.debug W/System.err:     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
2021-07-22 14:45:25.808 23287-23287/net.slions.fulguris.full.download.debug W/System.err:     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
2021-07-22 14:45:25.808 23287-23287/net.slions.fulguris.full.download.debug W/System.err:     at java.lang.Thread.run(Thread.java:764)
2021-07-22 14:45:25.925 23287-23292/net.slions.fulguris.full.download.debug I/zygote64: Compiler allocated 9MB to compile void android.widget.TextView.<init>(android.content.Context, android.util.AttributeSet, int, int)
2021-07-22 14:45:26.017 23287-23298/net.slions.fulguris.full.download.debug I/zygote64: Background concurrent copying GC freed 102264(3MB) AllocSpace objects, 9(280KB) LOS objects, 49% free, 10MB/20MB, paused 9.717ms total 190.872ms
2021-07-22 14:45:26.222 23287-23322/net.slions.fulguris.full.download.debug D/TransportRuntime.SQLiteEventStore: Storing event with priority=HIGHEST, name=FIREBASE_CRASHLYTICS_REPORT for destination cct
2021-07-22 14:45:26.256 23287-23322/net.slions.fulguris.full.download.debug D/TransportRuntime.JobInfoScheduler: Scheduling upload for context TransportContext(cct, HIGHEST, MSRodHRwczovL2NyYXNobHl0aWNzcmVwb3J0cy1wYS5nb29nbGVhcGlzLmNvbS92MS9maXJlbG9nL2xlZ2FjeS9iYXRjaGxvZ1xBSXphU3lCcnBTWVQ0RkZMMDlyZUhKaTZIOUZZZGVpU25VVE92Mk0=) with jobId=1197226322 in 11002ms(Backend next call timestamp 1626957937256). Attempt 1
2021-07-22 14:45:26.274 23287-23319/net.slions.fulguris.full.download.debug V/FA: Connecting to remote service
2021-07-22 14:45:26.343 23287-23319/net.slions.fulguris.full.download.debug V/FA: Recording user engagement, ms: 8243
2021-07-22 14:45:26.428 23287-23319/net.slions.fulguris.full.download.debug V/FA: Connection attempt already in progress
2021-07-22 14:45:46.903 23287-23382/net.slions.fulguris.full.download.debug D/AudioTrack: stop() called with 1420800 frames delivered
2021-07-22 14:45:51.905 23287-23382/net.slions.fulguris.full.download.debug D/AudioTrack: stop() called with 0 frames delivered
`

**Comment by Slion** [comment]
This was related to #222 and was fixed too.
