### ISSUE TITLE
Crash when tapping splash screen

### ISSUE THREAD

**Issue by Helium314** [Slion/Fulguris#285]
# Description
The browser crashes when tapping the splash screen during startup.

# Environment
 - Device: Samsung S4 mini
 - OS: Android 9 / LineageOS 16.0
 - Version: 1.7.17 (and older ones)

# To reproduce
Steps to reproduce the behaviour:
1. start browser
2. randomly tap on the splash screen
3. get a crash

# Expected behaviour
Browser starts normally

# Additional context
According to logs, the crash happens because `canScrollVertically(int)` is called on a null object in https://github.com/Slion/Fulguris/blob/ceb2b94c5039a25a7cb92a7df96bc1fa51da0655/app/src/main/java/acr/browser/lightning/browser/activity/BrowserActivity.kt#L3853
Indeed there is no crash if I insert following line above the quoted one:
```kotlin
        if (tabsManager.currentTab == null) return false
```

I'm not sure whether this is a good solution, as it seems more like a workaround (and I don't know what the return value does)

**Comment by Slion** [comment]
Good catch, though the crash is happening while the BrowserActivity is still loading apparently, which comes after the Splash screen activity is done. I just tried to reproduce it quick on my F(x)Tec Pro¹ with Lineage OS 18.1 but could not.
I'm guessing that's very much timing dependent and it might be easier to reproduce on slower devices.

Your S4 is seriously antiquated, good job on getting Android 9 to run on that. 😁

**Comment by Helium314** [comment]
You're right, when I tap "too late" (but still at splash screen) there is no crash, so the view loads at some point duing splash screen.

My phone might be old, but my requirements of OLED display and <= 65 mm width are apparently too strict. iPhone mini was the only alternative here in the past few years...

**Comment by Slion** [comment]
What about changing the declaration of our `canScrollVertically` extension?
Maybe something like that:
`fun View?.canScrollVertically() = this?.let {`
See what I did with the question marks?
Not sure both are needed though. Maybe only the later one on `this`.

**Comment by Helium314** [comment]
Crash log:
```
12-31 09:51:04.381 11549 11549 E AndroidRuntime: FATAL EXCEPTION: main
12-31 09:51:04.381 11549 11549 E AndroidRuntime: Process: net.slions.fulguris.full.fdroid, PID: 11549
12-31 09:51:04.381 11549 11549 E AndroidRuntime: java.lang.NullPointerException: Attempt to invoke virtual method 'boolean android.view.View.canScrollVertically(int)' on a null object reference
12-31 09:51:04.381 11549 11549 E AndroidRuntime: 	at androidx.swiperefreshlayout.widget.SwipeRefreshLayout.canChildScrollUp(SwipeRefreshLayout.java:6)
12-31 09:51:04.381 11549 11549 E AndroidRuntime: 	at androidx.swiperefreshlayout.widget.SwipeRefreshLayout.onInterceptTouchEvent(SwipeRefreshLayout.java:3)
12-31 09:51:04.381 11549 11549 E AndroidRuntime: 	at acr.browser.lightning.view.PullRefreshLayout.onInterceptTouchEvent(PullRefreshLayout.kt:10)
12-31 09:51:04.381 11549 11549 E AndroidRuntime: 	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2573)
12-31 09:51:04.381 11549 11549 E AndroidRuntime: 	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3030)
12-31 09:51:04.381 11549 11549 E AndroidRuntime: 	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2662)
12-31 09:51:04.381 11549 11549 E AndroidRuntime: 	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3030)
12-31 09:51:04.381 11549 11549 E AndroidRuntime: 	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2662)
12-31 09:51:04.381 11549 11549 E AndroidRuntime: 	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3030)
12-31 09:51:04.381 11549 11549 E AndroidRuntime: 	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2662)
12-31 09:51:04.381 11549 11549 E AndroidRuntime: 	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3030)
12-31 09:51:04.381 11549 11549 E AndroidRuntime: 	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2662)
12-31 09:51:04.381 11549 11549 E AndroidRuntime: 	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3030)
12-31 09:51:04.381 11549 11549 E AndroidRuntime: 	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2662)
12-31 09:51:04.381 11549 11549 E AndroidRuntime: 	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3030)
12-31 09:51:04.381 11549 11549 E AndroidRuntime: 	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2662)
12-31 09:51:04.381 11549 11549 E AndroidRuntime: 	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3030)
12-31 09:51:04.381 11549 11549 E AndroidRuntime: 	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2662)
12-31 09:51:04.381 11549 11549 E AndroidRuntime: 	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3030)
12-31 09:51:04.381 11549 11549 E AndroidRuntime: 	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2662)
12-31 09:51:04.381 11549 11549 E AndroidRuntime: 	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3030)
12-31 09:51:04.381 11549 11549 E AndroidRuntime: 	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2662)
12-31 09:51:04.381 11549 11549 E AndroidRuntime: 	at com.android.internal.policy.DecorView.superDispatchTouchEvent(DecorView.java:440)
12-31 09:51:04.381 11549 11549 E AndroidRuntime: 	at com.android.internal.policy.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1830)
12-31 09:51:04.381 11549 11549 E AndroidRuntime: 	at android.app.Activity.dispatchTouchEvent(Activity.java:3401)
12-31 09:51:04.381 11549 11549 E AndroidRuntime: 	at acr.browser.lightning.browser.activity.BrowserActivity.dispatchTouchEvent(BrowserActivity.kt:4)
12-31 09:51:04.381 11549 11549 E AndroidRuntime: 	at androidx.appcompat.view.WindowCallbackWrapper.dispatchTouchEvent(WindowCallbackWrapper.java:1)
12-31 09:51:04.381 11549 11549 E AndroidRuntime: 	at com.android.internal.policy.DecorView.dispatchTouchEvent(DecorView.java:398)
12-31 09:51:04.381 11549 11549 E AndroidRuntime: 	at android.view.View.dispatchPointerEvent(View.java:12752)
12-31 09:51:04.381 11549 11549 E AndroidRuntime: 	at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:5110)
12-31 09:51:04.381 11549 11549 E AndroidRuntime: 	at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:4913)
12-31 09:51:04.381 11549 11549 E AndroidRuntime: 	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4430)
12-31 09:51:04.381 11549 11549 E AndroidRuntime: 	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:4483)
12-31 09:51:04.381 11549 11549 E AndroidRuntime: 	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:4449)
12-31 09:51:04.381 11549 11549 E AndroidRuntime: 	at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:4589)
12-31 09:51:04.381 11549 11549 E AndroidRuntime: 	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:4457)
12-31 09:51:04.381 11549 11549 E AndroidRuntime: 	at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:4646)
12-31 09:51:04.381 11549 11549 E AndroidRuntime: 	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4430)
12-31 09:51:04.381 11549 11549 E AndroidRuntime: 	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:4483)
12-31 09:51:04.381 11549 11549 E AndroidRuntime: 	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:4449)
12-31 09:51:04.381 11549 11549 E AndroidRuntime: 	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:4457)
12-31 09:51:04.381 11549 11549 E AndroidRuntime: 	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4430)
12-31 09:51:04.381 11549 11549 E AndroidRuntime: 	at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:7096)
12-31 09:51:04.381 11549 11549 E AndroidRuntime: 	at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:7065)
12-31 09:51:04.381 11549 11549 E AndroidRuntime: 	at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:7026)
12-31 09:51:04.381 11549 11549 E AndroidRuntime: 	at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:7199)
12-31 09:51:04.381 11549 11549 E AndroidRuntime: 	at android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:186)
12-31 09:51:04.381 11549 11549 E AndroidRuntime: 	at android.os.MessageQueue.nativePollOnce(Native Method)
12-31 09:51:04.381 11549 11549 E AndroidRuntime: 	at android.os.MessageQueue.next(MessageQueue.java:326)
12-31 09:51:04.381 11549 11549 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:160)
12-31 09:51:04.381 11549 11549 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:6718)
12-31 09:51:04.381 11549 11549 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
12-31 09:51:04.381 11549 11549 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:491)
12-31 09:51:04.381 11549 11549 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
```

**Comment by Helium314** [comment]
> What about changing the declaration of our canScrollVertically extension?

I don't think this would help. You should see it in the logs if it was called, right?

**Comment by Slion** [comment]
I could reproduce it on my LG Leon.

```
2021-12-31 14:36:38.035 15266-15266/net.slions.fulguris.full.download.debug E/AndroidRuntime: FATAL EXCEPTION: main
    Process: net.slions.fulguris.full.download.debug, PID: 15266
    java.lang.NullPointerException: Attempt to invoke virtual method 'boolean android.view.View.canScrollVertically(int)' on a null object reference
        at androidx.swiperefreshlayout.widget.SwipeRefreshLayout.canChildScrollUp(SwipeRefreshLayout.java:678)
        at androidx.swiperefreshlayout.widget.SwipeRefreshLayout.onInterceptTouchEvent(SwipeRefreshLayout.java:701)
        at acr.browser.lightning.view.PullRefreshLayout.onInterceptTouchEvent(PullRefreshLayout.kt:72)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2150)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2597)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2239)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2597)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2239)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2597)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2239)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2597)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2239)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2597)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2239)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2597)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2239)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2597)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2239)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2597)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2239)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2597)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2239)
        at com.android.internal.policy.PhoneWindow$DecorView.superDispatchTouchEvent(PhoneWindow.java:2422)
        at com.android.internal.policy.PhoneWindow.superDispatchTouchEvent_aroundBody0(PhoneWindow.java:1754)
        at com.android.internal.policy.PhoneWindow$AjcClosure1.run(PhoneWindow.java:1)
        at android.view.PhoneWindowAO.ajc$around$android_view_PhoneWindowAO$4$99ce526bproceed(PhoneWindowAO.aj:149)
        at android.view.PhoneWindowAO.ajc$around$android_view_PhoneWindowAO$4$99ce526b(PhoneWindowAO.aj:153)
        at com.android.internal.policy.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1754)
        at android.app.Activity.dispatchTouchEvent(Activity.java:2800)
        at acr.browser.lightning.browser.activity.BrowserActivity.dispatchTouchEvent(BrowserActivity.kt:3961)
        at androidx.appcompat.view.WindowCallbackWrapper.dispatchTouchEvent(WindowCallbackWrapper.java:69)
        at com.android.internal.policy.PhoneWindow$DecorView.dispatchTouchEvent(PhoneWindow.java:2383)
        at android.view.View.dispatchPointerEvent(View.java:9527)
        at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:4416)
        at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:4282)
        at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3733)
        at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3786)
        at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3752)
        at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:3879)
        at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:3760)
        at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:3936)
        at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3733)
        at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3786)
        at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3752)
        at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:3760)
        at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3733)
        at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:6140)
    	at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.j
```

**Comment by Slion** [comment]
> I don't think this would help. You should see it in the logs if it was called, right?

Indeed, you were talking about a different function.

**Comment by Slion** [comment]
To me it's a bug in `androidx.swiperefreshlayout.widget.SwipeRefreshLayout`.

In `onInterceptTouchEvent` it calls `ensureTarget()` which in fact does not ensure any target and will cause the crash later on. ​

I guess we should sub class `SwipeRefreshLayout` to override `onInterceptTouchEvent`  and bailout if we can't find a target.
I think it's safer to do a proper fix here rather than just a workaround as I also do some nasty thing with the swipe refresh target  to implement the tabs animations.

See our extension: `SwipeRefreshLayout?.resetTarget`.

**Comment by Slion** [comment]
We should also report that to the Android Jetpack guys I guess.

**Comment by Slion** [comment]
Actually we already implement our own `̀PullRefreshLayout` class so I guess we could fix it in there. I'll give it a try.

**Comment by Slion** [comment]
See Slion/Fulguris#60

**Comment by Slion** [comment]
@Helium314 Hope that fixes it for you too. It did fix it on my LG Leon. Thanks again for reporting that issue and doing the initial investigation. Sorry for stepping in but I'll sleep better knowing we actually fixed the root cause rather than just workaround it.

**Comment by Helium314** [comment]
> @Helium314 Hope that fixes it for you too. It did fix it on my LG Leon. Thanks again for reporting that issue and doing the initial investigation. Sorry for stepping in but I'll sleep better knowing we actually fixed the root cause rather than just workaround it.

I'll try later, but I trust it's fixed.
FInding a better solution that I did is definitiely welcome!
