### ISSUE TITLE
Crash: Runtime exception using a recycled bitmap 

### ISSUE THREAD

**Issue by theriel** [Slion/Fulguris#376]
# Description

App randomly crashes when clicking on bookmarks with the following crash report:

 ```
java.lang.RuntimeException: Canvas: trying to use a recycled bitmap android.graphics.Bitmap@12cf865
	at android.graphics.BaseCanvas.throwIfCannotDraw(BaseCanvas.java:72)
	at android.graphics.RecordingCanvas.throwIfCannotDraw(RecordingCanvas.java:282)
	at android.graphics.BaseRecordingCanvas.drawBitmap(BaseRecordingCanvas.java:127)
	at android.graphics.drawable.BitmapDrawable.draw(BitmapDrawable.java:555)
	at android.widget.ImageView.onDraw(ImageView.java:1444)
	at android.view.View.draw(View.java:22528)
	at android.view.View.updateDisplayListIfDirty(View.java:21389)
	at android.view.View.draw(View.java:22254)
	at android.view.ViewGroup.drawChild(ViewGroup.java:4541)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4302)
	at android.view.View.updateDisplayListIfDirty(View.java:21380)
	at android.view.View.draw(View.java:22254)
	at android.view.ViewGroup.drawChild(ViewGroup.java:4541)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4302)
	at android.view.View.draw(View.java:22538)
	at android.view.View.updateDisplayListIfDirty(View.java:21389)
	at android.view.View.draw(View.java:22254)
	at android.view.ViewGroup.drawChild(ViewGroup.java:4541)
	at androidx.recyclerview.widget.RecyclerView.drawChild(Unknown Source:0)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4302)
	at android.view.View.draw(View.java:22663)
	at androidx.recyclerview.widget.RecyclerView.draw(Unknown Source:0)
	at android.view.View.updateDisplayListIfDirty(View.java:21389)
	at android.view.View.draw(View.java:22254)
	at android.view.ViewGroup.drawChild(ViewGroup.java:4541)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4302)
	at android.view.View.draw(View.java:22538)
	at android.view.View.updateDisplayListIfDirty(View.java:21389)
	at android.view.View.draw(View.java:22254)
	at android.view.ViewGroup.drawChild(ViewGroup.java:4541)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4302)
	at android.view.View.updateDisplayListIfDirty(View.java:21380)
	at android.view.View.draw(View.java:22254)
	at android.view.ViewGroup.drawChild(ViewGroup.java:4541)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4302)
	at android.view.View.draw(View.java:22538)
	at android.view.View.updateDisplayListIfDirty(View.java:21389)
	at android.view.View.draw(View.java:22254)
	at android.view.ViewGroup.drawChild(ViewGroup.java:4541)
	at androidx.drawerlayout.widget.DrawerLayout.drawChild(:2)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4302)
	at android.view.View.draw(View.java:22538)
	at android.view.View.updateDisplayListIfDirty(View.java:21389)
	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4525)
	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4498)
	at android.view.View.updateDisplayListIfDirty(View.java:21349)
	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4525)
	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4498)
	at android.view.View.updateDisplayListIfDirty(View.java:21349)
	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4525)
	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4498)
	at android.view.View.updateDisplayListIfDirty(View.java:21349)
	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4525)
	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4498)
	at android.view.View.updateDisplayListIfDirty(View.java:21349)
	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4525)
	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4498)
	at android.view.View.updateDisplayListIfDirty(View.java:21349)
	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4525)
	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4498)
	at android.view.View.updateDisplayListIfDirty(View.java:21349)
	at android.view.ThreadedRenderer.updateViewTreeDisplayList(ThreadedRenderer.java:559)
	at android.view.ThreadedRenderer.updateRootDisplayList(ThreadedRenderer.java:565)
	at android.view.ThreadedRenderer.draw(ThreadedRenderer.java:647)
	at android.view.ViewRootImpl.draw(ViewRootImpl.java:4417)
	at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:4144)
	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:3391)
	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:2182)
	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:8730)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1352)
	at android.view.Choreographer.doCallbacks(Choreographer.java:1149)
	at android.view.Choreographer.doFrame(Choreographer.java:1049)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1333)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:233)
	at android.app.ActivityThread.main(ActivityThread.java:8010)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:631)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:978)
 ```

# Environment
 - Device: Oneplus 7 Pro
 - OS: Android 11
 - Version: 1.8.7

**Comment by Slion** [comment]
Thanks for reporting this issue. Is it happening when opening the bookmarks drawer or the tabs drawer or both?

**Comment by Slion** [comment]
Those crashes have been there for a long time I believe and Fulguris is not the only application having [such issues](https://stackoverflow.com/questions/22129420/canvas-trying-to-use-a-recycled-bitmap-android-graphics-bitmap-in-android).

    I inspected the code again and could not find a call to `Bitmap.recycle` that would cause those issues. So I went ahead and deployed [something to avoid the crash](https://stackoverflow.com/questions/22129420/canvas-trying-to-use-a-recycled-bitmap-android-graphics-bitmap-in-android) but it could also result in incomplete drawings.
