### ISSUE TITLE
java.lang.IllegalArgumentException: Activity client record must not be null to execute transaction item

### ISSUE THREAD

**Issue by DionGanteng** [Slion/Fulguris#389]
Force close application only happens on android 12

# Description
java.lang.IllegalArgumentException: Activity client record must not be null to execute transaction item
        at android.app.servertransaction.ActivityTransactionItem.getActivityClientRecord(ActivityTransactionItem.java:85)
        at android.app.servertransaction.ActivityTransactionItem.getActivityClientRecord(ActivityTransactionItem.java:58)
        at android.app.servertransaction.ActivityTransactionItem.execute(ActivityTransactionItem.java:43)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2442)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loopOnce(Looper.java:233)
        at android.os.Looper.loop(Looper.java:334)
        at android.app.ActivityThread.main(ActivityThread.java:8442)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:582)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1068)

**Comment by Slion** [comment]
When does that crash happen? Do you have steps to reproduce it? Which device are you using?

**Comment by DionGanteng** [comment]
All variants and apps crash when starting, from some information sites it's an android 12 bug, but I don't know, still not getting an answer
