### ISSUE TITLE
Crashes on new tab when you have a / in the bookmark folder name

### ISSUE THREAD

**Issue by WTechNinja** [Slion/Fulguris#411]
# Description
I added a bookmark to the Information/Github folder, and everything seemed fine until I made a new tab, and then it crashed. Even worse, if you clear all tabs so that it makes a new tab on start, you can't use the app.

# Environment
 - Device: Samsing Galaxy S8
 - OS: Android 9
 - Version: 1.8.8 from Fdroid

# To reproduce
Steps to reproduce the behaviour:
1. Go to 'Bookmarks"
2. Edit one of them to have the folder be "Information/Github"
3. Make a new tab
4. App dies

# Expected behaviour
No crash

# Additional context
Here's the log

FATAL EXCEPTION: main
Process: net.slions.fulguris.full.fdroid, PID: 10839
a5.c: The exception was not handled due to missing onError handler in the subscribe() method call. Further reading: https://github.com/ReactiveX/RxJava/wiki/Error-Handling | java.io.FileNotFoundException: /data/user/0/net.slions.fulguris.full.fdroid/files/Information/Github-bookmarks.html (No such file or directory)
	at e5.a$f.d(Unknown Source:4)
	at g5.d.a(Unknown Source:7)
	at l5.k$a.run(Unknown Source:6)
	at y4.b$b.run(Unknown Source:2)
	at android.os.Handler.handleCallback(Handler.java:873)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:214)
	at android.app.ActivityThread.main(ActivityThread.java:7050)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:494)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:964)
Caused by: java.io.FileNotFoundException: /data/user/0/net.slions.fulguris.full.fdroid/files/Information/Github-bookmarks.html (No such file or directory)
	at java.io.FileOutputStream.open0(Native Method)
	at java.io.FileOutputStream.open(FileOutputStream.java:308)
	at java.io.FileOutputStream.<init>(FileOutputStream.java:238)
	at java.io.FileWriter.<init>(FileWriter.java:107)
	at a.c.d(SourceFile:7)
	at k5.c$a.f(Unknown Source:7)
	at k5.i$a.run(SourceFile:2)
	at n5.b$c$a.run(Unknown Source:10)
	at n5.b$c.run(Unknown Source:37)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:764)

I'm loving this browser otherwise though. Only thing I'd like added is subfolders lol

**Comment by Helium314** [comment]
Looks like either the folder name should be checked for invalid characters using an `onTextChangedListener` near https://github.com/Slion/Fulguris/blob/24c32639900af0235707a443465e6ccca2f8106b/app/src/main/java/acr/browser/lightning/dialog/LightningDialogBuilder.kt#L223-L225
or String.asFolder should somehow escape / encode such characters: https://github.com/Slion/Fulguris/blob/24c32639900af0235707a443465e6ccca2f8106b/app/src/main/java/acr/browser/lightning/database/WebPage.kt#L89
