### ISSUE TITLE
Random crash opening link from outside app

### ISSUE THREAD

**Issue by WTechNinja** [Slion/Fulguris#413]
# Description
Crashes when opening link from another app. Doesn't matter which app, and I can't figure out how to reproduce it because it occurs pretty randomly, and with all sorts of links.

# Environment
 - Device: Samsung Galaxy S8
 - OS: Android 9
 - Version: 1.8.12

# To reproduce
Steps to reproduce the behaviour:
1. Click on a link in another app
2. Browser launches and crashes immediately

# Expected behaviour
App doesn't crash, just makes new tab and shows it normally 

# Additional context
The browser works just fine if I click the link again, and launch the browser a second time.
I know full well my phone kills apps in the background so it could be related to that, but I'm no dev. Here are the stack traces from the crashes though:

<details><summary>First Crash</summary><p>

```
FATAL EXCEPTION: main
Process: net.slions.fulguris.full.fdroid, PID: 27496
java.lang.IndexOutOfBoundsException: Index: -1, Size: 11
	at java.util.ArrayList.add(ArrayList.java:483)
	at acr.browser.lightning.browser.TabsManager.r(Unknown Source:84)
	at acr.browser.lightning.browser.BrowserPresenter.m(SourceFile:5)
	at f.b.c(SourceFile:11)
	at acr.browser.lightning.browser.TabsManager$c.a(Unknown Source:2)
	at f.c.h(SourceFile:20)
	at m6.a.j(SourceFile:2)
	at h4.d.B(Unknown Source:47)
	at c7.j.t(SourceFile:7)
	at c7.j.D(Unknown Source:42)
	at c7.j.l(Unknown Source:25)
	at d7.a$a.run(Unknown Source:4)
	at android.os.Handler.handleCallback(Handler.java:873)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:214)
	at android.app.ActivityThread.main(ActivityThread.java:7050)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:494)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:964)
```

</p></details>

<details><summary>Second Crash</summary><p>

```
FATAL EXCEPTION: main
Process: net.slions.fulguris.full.fdroid, PID: 13485
java.lang.IndexOutOfBoundsException: Index: -1, Size: 24
	at java.util.ArrayList.add(ArrayList.java:483)
	at acr.browser.lightning.browser.TabsManager.r(Unknown Source:84)
	at acr.browser.lightning.browser.BrowserPresenter.m(SourceFile:5)
	at f.b.c(SourceFile:11)
	at acr.browser.lightning.browser.TabsManager$c.a(Unknown Source:2)
	at f.c.h(SourceFile:20)
	at m6.a.j(SourceFile:2)
	at h4.d.B(Unknown Source:47)
	at c7.j.t(SourceFile:7)
	at c7.j.D(Unknown Source:42)
	at c7.j.l(Unknown Source:25)
	at d7.a$a.run(Unknown Source:4)
	at android.os.Handler.handleCallback(Handler.java:873)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:214)
	at android.app.ActivityThread.main(ActivityThread.java:7050)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:494)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:964)
```

</p></details>

**Comment by Slion** [comment]
Thanks for that bug report. Looks like something does need fixing there.

**Comment by tigerknight** [comment]
I am also experiencing this crash.  The crash can be invoked from Fulguris itself:
- Menu &rarr; Settings &rarr; Contribute &rarr; Sponsor us on Github

Fortunately, after Fulguris relaunches from the crash, it's able to recover all its active tabs.  Immediately reopening a link from the outside app will not invoke the crash for a while.

### Environment

- Device: Nokia 6.1
- OS: Android 8.1.0
- Fulguris version: 1.8.17
- WebView version: 109.0.5414.117

### Crash logs

- All logs for this crash are identical, other than line 17, `waitForConnection(SQLiteConnectionPool.java:731)` or `waitForConnection(SQLiteConnectionPool.java:653)`, which seems to alternate at random

<details>
<summary>Log 1</summary>

```
p7.c: The exception was not handled due to missing onError handler in the subscribe() method call. Further reading: https://github.com/ReactiveX/RxJava/wiki/Error-Handling | java.lang.IllegalStateException: Cannot perform this operation because the connection pool has been closed.
	at t7.a$f.accept(Unknown Source:4)
	at d8.c.a(Unknown Source:13)
	at x7.w$a.e(Unknown Source:33)
	at x7.w$c.m(Unknown Source:29)
	at x7.w$a.run(Unknown Source:17)
	at n7.b$b.run(Unknown Source:2)
	at android.os.Handler.handleCallback(Handler.java:790)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:164)
	at android.app.ActivityThread.main(ActivityThread.java:6501)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
Caused by: java.lang.IllegalStateException: Cannot perform this operation because the connection pool has been closed.
	at android.database.sqlite.SQLiteConnectionPool.throwIfClosedLocked(SQLiteConnectionPool.java:1034)
	at android.database.sqlite.SQLiteConnectionPool.waitForConnection(SQLiteConnectionPool.java:653)
	at android.database.sqlite.SQLiteConnectionPool.acquireConnection(SQLiteConnectionPool.java:369)
	at android.database.sqlite.SQLiteSession.acquireConnection(SQLiteSession.java:894)
	at android.database.sqlite.SQLiteSession.executeForCursorWindow(SQLiteSession.java:834)
	at android.database.sqlite.SQLiteQuery.fillWindow(SQLiteQuery.java:62)
	at android.database.sqlite.SQLiteCursor.fillWindow(SQLiteCursor.java:143)
	at android.database.sqlite.SQLiteCursor.getCount(SQLiteCursor.java:132)
	at android.database.AbstractCursor.moveToPosition(AbstractCursor.java:220)
	at android.database.AbstractCursor.moveToNext(AbstractCursor.java:269)
	at h.h.call(SourceFile:7)
	at a8.g.k(Unknown Source:18)
	at m7.m.c(SourceFile:2)
	at x7.k$a.g(SourceFile:2)
	at x7.b0$b.g(Unknown Source:2)
	at x7.z$b.d(Unknown Source:122)
	at x7.z$b.g(Unknown Source:23)
	at x7.j$b.h(Unknown Source:28)
	at x7.j$b.g(Unknown Source:0)
	at x7.v$a.g(SourceFile:2)
	at x7.x$a.d(Unknown Source:49)
	at x7.x$a.g(Unknown Source:5)
	at x7.n$a.g(Unknown Source:2)
	at z7.f$a.g(Unknown Source:2)
	at k8.b.g(SourceFile:3)
	at o0.f$a.performFiltering(Unknown Source:26)
	at android.widget.Filter$RequestHandler.handleMessage(Filter.java:234)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loop(Looper.java:164)
	at android.os.HandlerThread.run(HandlerThread.java:65)
``` 
</details>

<details>
<summary>Log 2</summary>

```
p7.c: The exception was not handled due to missing onError handler in the subscribe() method call. Further reading: https://github.com/ReactiveX/RxJava/wiki/Error-Handling | java.lang.IllegalStateException: Cannot perform this operation because the connection pool has been closed.
	at t7.a$f.accept(Unknown Source:4)
	at d8.c.a(Unknown Source:13)
	at x7.w$a.e(Unknown Source:33)
	at x7.w$c.m(Unknown Source:29)
	at x7.w$a.run(Unknown Source:17)
	at n7.b$b.run(Unknown Source:2)
	at android.os.Handler.handleCallback(Handler.java:790)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:164)
	at android.app.ActivityThread.main(ActivityThread.java:6501)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
Caused by: java.lang.IllegalStateException: Cannot perform this operation because the connection pool has been closed.
	at android.database.sqlite.SQLiteConnectionPool.throwIfClosedLocked(SQLiteConnectionPool.java:1034)
	at android.database.sqlite.SQLiteConnectionPool.waitForConnection(SQLiteConnectionPool.java:731)
	at android.database.sqlite.SQLiteConnectionPool.acquireConnection(SQLiteConnectionPool.java:369)
	at android.database.sqlite.SQLiteSession.acquireConnection(SQLiteSession.java:894)
	at android.database.sqlite.SQLiteSession.executeForCursorWindow(SQLiteSession.java:834)
	at android.database.sqlite.SQLiteQuery.fillWindow(SQLiteQuery.java:62)
	at android.database.sqlite.SQLiteCursor.fillWindow(SQLiteCursor.java:143)
	at android.database.sqlite.SQLiteCursor.getCount(SQLiteCursor.java:132)
	at android.database.AbstractCursor.moveToPosition(AbstractCursor.java:220)
	at android.database.AbstractCursor.moveToNext(AbstractCursor.java:269)
	at h.h.call(SourceFile:7)
	at a8.g.k(Unknown Source:18)
	at m7.m.c(SourceFile:2)
	at x7.k$a.g(SourceFile:2)
	at x7.b0$b.g(Unknown Source:2)
	at x7.z$b.d(Unknown Source:122)
	at x7.z$b.g(Unknown Source:23)
	at x7.j$b.h(Unknown Source:28)
	at x7.j$b.g(Unknown Source:0)
	at x7.v$a.g(SourceFile:2)
	at x7.x$a.d(Unknown Source:49)
	at x7.x$a.g(Unknown Source:5)
	at x7.n$a.g(Unknown Source:2)
	at z7.f$a.g(Unknown Source:2)
	at k8.b.g(SourceFile:3)
	at o0.f$a.performFiltering(Unknown Source:26)
	at android.widget.Filter$RequestHandler.handleMessage(Filter.java:234)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loop(Looper.java:164)
	at android.os.HandlerThread.run(HandlerThread.java:65)
```
</details>
