### ISSUE TITLE
The browser crashes when I delete cookies

### ISSUE THREAD

**Issue by alan-ford** [Slion/Fulguris#566]
# Description
The 32-bit release of the browser (armeabi-v7a) crashes when I delete cookies.

# Environment
 - Device: Amazon Fire 7
 - OS: Lineage
 - Version: 14.1

# To reproduce
Steps to reproduce the behaviour:
1. Open browser
2. Tap on thunder
3. Tap on "Settings"
4. Tap on "Privacy"
5. Tap on "Clear browser cookies"
6. Tap on "Yes"

**Comment by Slion** [comment]
Can you get the crash logs? Settings / Debug / Crash logs then find the proper file from timestamp and post the content here.

**Comment by alan-ford** [comment]
@Slion  I activated the log, where is the file saved?

**Comment by Slion** [comment]
Tap on the crash logs settings item it should open the folder. If it does not you may want to install a file manager app that supports that functionality such as File Manager + for instance.

**Comment by alan-ford** [comment]
@Slion  Here

`m5.d: The exception was not handled due to missing onError handler in the subscribe() method call. Further reading: https://github.com/ReactiveX/RxJava/wiki/Error-Handling | java.lang.IllegalStateException: removeAllCookies must be called on a thread with a running Looper.
	at s5.c.accept(SourceFile:5)
	at s5.c.a(SourceFile:1)
	at t5.c.run(SourceFile:18)
	at k5.e.run(SourceFile:1)
	at android.os.Handler.handleCallback(Handler.java:751)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at android.os.Looper.loop(Looper.java:154)
	at android.app.ActivityThread.main(ActivityThread.java:6186)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:889)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:779)
Caused by: java.lang.IllegalStateException: removeAllCookies must be called on a thread with a running Looper.
	at Uh.removeAllCookies(chromium-SystemWebView.apk-default-438910503:5)
	at s0.a0.run(SourceFile:54)
	at t5.b.l0(SourceFile:21)
	at k8.a.k0(SourceFile:3)
	at t5.c.run(SourceFile:30)
	at z5.s.call(SourceFile:12)
	at java.util.concurrent.FutureTask.run(FutureTask.java:237)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
	at java.lang.Thread.run(Thread.java:761)`

**Comment by Slion** [comment]
Thanks, Actually I saw that bug a few days back in Firebase. Was probably you cause I recall it was Fire Amazon device.

**Comment by Yuri-VK** [comment]
I can guarantee that this error occurs on a device with Android 9 (Huawei P Smart) when using browser version 1.9.17.

**Comment by Slion** [comment]
Crashlytics [report](https://console.firebase.google.com/u/0/project/fulguris-b1f69/crashlytics/app/android:net.slions.fulguris.full.download/issues/20d157d7c5d5b1a22fe5ca430bbae935?time=last-seven-days&sessionEventKey=65A9AE2C015D00014A7A2A1580743086_1904023466297098530).

**Comment by Slion** [comment]
This is a regression introduced in d74f794d17c52a1957e7652087e1a074ea2b637f
