### ISSUE TITLE
Browser crashes when opening new tab

### ISSUE THREAD

**Issue by OmegaSunkey** [Slion/Fulguris#593]
# Description
The browser crashes when opening a new tab

# Environment
 - Device: Infinix Hot 10 Lite - X657B
 - OS: Android 10
 - Version: 1.9.17

# To reproduce
Steps to reproduce the behaviour:
1. Go to Settings > Backup
2. Import bookmarks that were exported from other browser
3. Open a new tab

# Expected behaviour
It should just open a new tab.

# Additional context
The browser that exported the bookmarks was DuckDuckGo Privacy Browser.
The problem can be fixed by changing what's shown on the homepage on settings, but the user won't be able to view their bookmarks on homepage.
The crashlog:
```
FATAL EXCEPTION: main
Process: net.slions.fulguris.full.fdroid, PID: 24645
m5.d: The exception was not handled due to missing onError handler in the subscribe() method call. Further reading: https://github.com/ReactiveX/RxJava/wiki/Error-Handling | java.io.FileNotFoundException: /data/user/0/net.slions.fulguris.full.fdroid/files/DuckDuckGo Bookmarks/h-bookmarks.html: open failed: ENOENT (No such file or directory)
	at q5.c.accept(SourceFile:12)
	at s5.d.a(SourceFile:16)
	at x5.j.run(SourceFile:1)
	at k5.e.run(SourceFile:1)
	at android.os.Handler.handleCallback(Handler.java:883)
	at android.os.Handler.dispatchMessage(Handler.java:100)
	at android.os.Looper.loop(Looper.java:264)
	at android.app.ActivityThread.main(ActivityThread.java:7663)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:980)
Caused by: java.io.FileNotFoundException: /data/user/0/net.slions.fulguris.full.fdroid/files/DuckDuckGo Bookmarks/h-bookmarks.html: open failed: ENOENT (No such file or directory)
	at libcore.io.IoBridge.open(IoBridge.java:496)
	at java.io.FileOutputStream.<init>(FileOutputStream.java:235)
	at java.io.FileWriter.<init>(FileWriter.java:107)
	at b0.b.k(SourceFile:292)
	at h.g.accept(SourceFile:88)
	at w5.d.e(SourceFile:1)
	at w5.p.run(SourceFile:120)
	at z5.f.run(SourceFile:1)
	at z5.h.run(SourceFile:1)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:919)
Caused by: android.system.ErrnoException: open failed: ENOENT (No such file or directory)
	at libcore.io.Linux.open(Native Method)
	at libcore.io.ForwardingOs.open(ForwardingOs.java:167)
	at libcore.io.BlockGuardOs.open(BlockGuardOs.java:252)
	at libcore.io.ForwardingOs.open(ForwardingOs.java:167)
	at android.app.ActivityThread$AndroidOs.open(ActivityThread.java:7556)
	at libcore.io.IoBridge.open(IoBridge.java:482)
	... 11 more
```

**Comment by Slion** [comment]
Interesting, looks like the imported bookmarks are breaking the page.

**Comment by Slion** [comment]
Bookmarks import from DDG worked fine for me.
Can you provide the HTML file you used to import?

**Comment by Slion** [comment]
Ok so the issue is with sub folders. If you import an HTML bookmarks file with nested folders it breaks.
