### ISSUE TITLE
Website causes Fulguris to crash

### ISSUE THREAD

**Issue by OmegaSunkey** [Slion/Fulguris#596]
# Description
A website called gk.city causes Fulguris to crash after **trying** to load it.

# Environment
 - Device: Infinix Hot 10 Lite — X657B
 - OS: Android 10
 - Version: 1.9.17

# To reproduce
Steps to reproduce the behaviour:
1. Go to https://gk.city/2022/09/25/estos-son-derechos-pueblos-nacionalidades-indigenas-ecuador/

# Expected behaviour
It should open the website. 

# Additional context
The website loads without problems on Chrome.
The crashlog:
```
FATAL EXCEPTION: main
Process: net.slions.fulguris.full.fdroid, PID: 2265
java.lang.IllegalArgumentException: Invalid URL host: "jsc.mgid.com, 824917, direct, d4c29acad76ce94f.js"
	at u7.v.h(SourceFile:806)
	at t0.d.<init>(SourceFile:59)
	at x0.e0.d(SourceFile:95)
	at x0.e0.onLoadResource(SourceFile:1)
	at WV.jY.a(chromium-TrichromeWebViewGoogle.aab-stable-609919430:12)
	at WV.B6.handleMessage(chromium-TrichromeWebViewGoogle.aab-stable-609919430:513)
	at android.os.Handler.dispatchMessage(Handler.java:107)
	at android.os.Looper.loop(Looper.java:264)
	at android.app.ActivityThread.main(ActivityThread.java:7663)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:980)
```

**Comment by Slion** [comment]
Thanks I can reproduce the issue. Definitely something specific to Fulguris. It works on DuckDuckGo for instance. It has to do with our domain settings implementation.

**Comment by Slion** [comment]
This issue was caused by a web page attempting to load a resource with a malformed URL.
In this case: 
`https://jsc.mgid.com%2C%20824917%2C%20direct%2C%20d4c29acad76ce94f.js/`
Which translates to invalid domain:
`jsc.mgid.com, 824917, direct, d4c29acad76ce94f.js`

In this case we just load the default domain preferences. Not that it matters much though, but at least we don't crash anymore.
