### ISSUE TITLE
Cookies are not cleared

### ISSUE THREAD

**Issue by Slion** [Slion/Fulguris#597]
When trying to clear cookies from privacy settings you get the following exception:

```
io.reactivex.exceptions.OnErrorNotImplementedException: The exception was not handled due to missing onError handler in the subscribe() method call. Further reading: https://github.com/ReactiveX/RxJava/wiki/Error-Handling | java.lang.IllegalStateException: removeAllCookies must be called on a thread with a running Looper.
	at io.reactivex.internal.observers.CallbackCompletableObserver.accept(CallbackCompletableObserver.java:47)
	at io.reactivex.internal.observers.CallbackCompletableObserver.accept(CallbackCompletableObserver.java:26)
	at io.reactivex.internal.observers.CallbackCompletableObserver.onError(CallbackCompletableObserver.java:64)
	at io.reactivex.internal.operators.completable.CompletableObserveOn$ObserveOnCompletableObserver.run(CompletableObserveOn.java:87)
	at io.reactivex.android.schedulers.HandlerScheduler$ScheduledRunnable.run(HandlerScheduler.java:124)
	at android.os.Handler.handleCallback(Handler.java:900)
	at android.os.Handler.dispatchMessage(Handler.java:103)
	at android.os.Looper.loop(Looper.java:219)
	at android.app.ActivityThread.main(ActivityThread.java:8668)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:513)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1109)
Caused by: java.lang.IllegalStateException: removeAllCookies must be called on a thread with a running Looper.
	at com.android.webview.chromium.a.removeAllCookies(chromium-TrichromeWebViewGoogle6432.aab-stable-609921033:42)
	at fulguris.utils.WebUtils.clearCookies(WebUtils.kt:17)
	at fulguris.settings.fragment.PrivacySettingsFragment.clearCookies$lambda$2(PrivacySettingsFragment.kt:189)
	at fulguris.settings.fragment.PrivacySettingsFragment.$r8$lambda$tOO8VjnmihWRu7zqYhxN0FWgT2U(Unknown Source:0)
	at fulguris.settings.fragment.PrivacySettingsFragment$$ExternalSyntheticLambda1.run(Unknown Source:2)
	at io.reactivex.internal.operators.completable.CompletableFromAction.subscribeActual(CompletableFromAction.java:35)
	at io.reactivex.Completable.subscribe(Completable.java:2309)
	at io.reactivex.internal.operators.completable.CompletableSubscribeOn$SubscribeOnObserver.run(CompletableSubscribeOn.java:64)
	at io.reactivex.internal.schedulers.ScheduledDirectTask.call(ScheduledDirectTask.java:38)
	at io.reactivex.internal.schedulers.ScheduledDirectTask.call(ScheduledDirectTask.java:26)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:929)
```

**Comment by Slion** [comment]
Duplicate of #566
